version: '3.8'

volumes:
  db_storage:
  n8n_storage:

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dbteste
      - POSTGRES_NON_ROOT_USER=admin
      - POSTGRES_NON_ROOT_PASSWORD=admin
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U admin -d dbteste']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=dbteste
      - DB_POSTGRESDB_USER=admin
      - DB_POSTGRESDB_PASSWORD=admin
      - N8N_CUSTOM_EXTENSIONS=/opt/custom-nodes
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./dist:/opt/custom-nodes:ro
    depends_on:
      postgres:
        condition: service_healthy